"""Added URL table.

Revision ID: 7f43b7287a1e
Revises: 
Create Date: 2022-07-29 02:04:24.506667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f43b7287a1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('short_url', sa.String(length=10), nullable=False),
    sa.Column('long_url', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pkurls')),
    sa.UniqueConstraint('short_url', name=op.f('uqurlsshort_url'))
    )
    op.create_index('idx_short_url', 'urls', ['short_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_short_url', table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
